#ifndef CONFIG_H
#define CONFIG_H

#define EMULATOR_WINDOW_TITLE "CHIP8 Emulator"
#define CHIP8_MEMORY_SIZE 4096
#define CHIP8_WIDTH 64
#define CHIP8_HEIGHT 32
#define EMULATOR_WINDOW_SCALE 10
#define CHIP8_TOTAL_DATA_REGISTERS 16
#define CHIP8_STACK_SIZE 16
#define CHIP8_TOTAL_KEYS 16
#define CHIP8_CHARACTER_SET_LOAD_ADDR 0x00
#define CHIP8_PROGRAM_LOAD_ADDR 0x200
#define CHIP8_HRIGHT_OF_SPRITE 5U
#define CHIP8_SIZE_OF_INSTRUCTION 2
#define CHIP8_MAX_ARGUMENTS 3

#endif